s1 = set()
n1 =int(input("enter the first number:"))
s1.add(n1)
# print(s1)
n2 =int(input("enter the second number:"))
s1.add(n2)
n3 =int(input("enter the third number:"))
s1.add(n3)
n4 =int(input("enter the fourth number:"))
s1.add(n4)
n5 =int(input("enter the fifth number:"))
s1.add(n5)
n6 =int(input("enter the sixth number:"))
s1.add(n6)
n7 =int(input("enter the seventh number:"))
s1.add(n7)

print(s1)